parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  node: true
  es6: true
  mocha: true
parser: babel-eslint
extends:
  - standard
  - plugin:lodash/recommended
plugins:
  - import
  - lodash
globals:
  expect: false
rules:
  no-console: warn
  comma-dangle: off

  import/named: error
  import/namespace: error

  lodash/import-scope: off
